### ISSUE TITLE
Where to enter API key?

### ISSUE THREAD

**Issue by p6002** [richardyc/Chrome-GPT#27]
Where exactly to enter the api key, I could not find information anywhere.

**Comment by elio1fiore** [comment]
you can find information about #14 
enter it on the command line.

Search google or ask chatgpt how you can do.
Just look up how to insert an env variable.

I use mc the problem raised in 14 solved my doubt. If you're using windows it will be similar.

**Comment by p6002** [comment]
Unfortunately I am unable to get the project up and running due to lack of correct documentation and operating rules. 
I don't understand why I have to add env to Windows when I have the tool in docker on Ubuntu node install. 
Too many unknowns, I'm off to test other projects.
