### ISSUE TITLE
Non-continuous mode (asks for review/change intent)

### ISSUE THREAD

**Issue by DamascusGit** [richardyc/Chrome-GPT#3]
Can you port over the semi/non-continuous mode features from the auto-gpt repo to this, so we can change the model's task/directives/direction every N responses?

**Comment by richardyc** [comment]
Added for [auto-gpt agent](https://github.com/richardyc/Chrome-GPT/commit/0e608d4a2e4d3aca034714e53ccd2ab693d7a2da).
Usage: `python -m chromegpt -v -a auto-gpt --human-in-loop -t "{your request}"`

**Comment by DamascusGit** [comment]
can we set this to loop a certain amount of times during the input? like can I do -N 5 during the input to let it run freely for 5 inferences?
