### ISSUE TITLE
Error: Got unexpected extra argument ()

### ISSUE THREAD

**Issue by korean-1** [richardyc/Chrome-GPT#32]
(chrome-gpt-py3.11) PS C:\Users\Administrator\Desktop\git\chrome-gpt> python -m chromegpt -t open youtube
Usage: python -m chromegpt [OPTIONS]
Try 'python -m chromegpt --help' for help.

Error: Got unexpected extra argument (youtube)
(chrome-gpt-py3.11) PS C:\Users\Administrator\Desktop\git\chrome-gpt> 

No matter what command I run, it always says it can't run because it has too many arguments.
Any idea how to fix it?

**Comment by richardyc** [comment]
Thanks for trying the tool out! I think you need to wrap the command in quotes, e.g. `python -m chromegpt -t "open youtube"`

**Comment by korean-1** [comment]
thank you very much!!!!!!!!!!! it work well!!!
